Vanessa219/vditor

- src/ts/types/index.d.ts
- src/ts/wysiwyg/afterRenderEvent.ts
- src/ts/wysiwyg/index.ts
- src/ts/wysiwyg/processKeydown.ts
> 🧭 Safari 兼容性增强

- package.json
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html
之前
之后
> fix: publish type declaration file

- src/index.ts
- src/ts/ir/process.ts
- src/ts/resize/index.ts
- src/ts/sv/inputEvent.ts
- src/ts/toolbar/Fullscreen.ts
- src/ts/ui/initUI.ts
- src/ts/ui/setTheme.ts
- src/ts/wysiwyg/afterRenderEvent.ts
- types/index.d.ts
> 支持直接使用 Element 初始化

- src/ts/upload/index.ts
- types/index.d.ts
* options.upload 增加额外请求参数 extraData
> upload配置项添加额外请求参数

- src/ts/util/fixBrowserBehavior.ts
https://github.com/Vanessa219/vditor/issues/413
typora
New Vditor
> delete tables when cells are empty

- src/ts/upload/index.ts
阿里云oss上传必须是 `key` 做为第一个参数，因此调整一下顺序
* PR 请提交到开发分支上
* 我们对编码风格有着较为严格的要求，请在阅读代码后模仿类似风格提交
> fix: support aliyun oss

- CHANGELOG.md
- README.md
- README_en_US.md
- demo/index.html
- demo/index.js
- demo/render.html
- src/ts/ir/processKeydown.ts
- src/ts/util/fixBrowserBehavior.ts
- src/ts/util/selection.ts
- src/ts/wysiwyg/input.ts
1. 复制文本后粘贴光标位置错误
2. 粘贴时敲回车会出现文本添加位置错误
**注：只修改了即时渲染模式，所见即所得模式不确定是否有问题**
> 修复即时渲染模式下复制光标位置错误和添加位置错误的问题

- src/ts/util/fixBrowserBehavior.ts
Reverts Vanessa219/vditor#644
这个代码好像自己原地翻滚了下。我来处理吧。
> Revert "粘贴多行代码时，避免代码段的 ``` 与当前行内容混淆在一起"

- src/assets/scss/_reset.scss
- src/ts/ir/index.ts
- src/ts/ir/process.ts
- src/ts/toolbar/MenuItem.ts
- src/ts/util/compatibility.ts
问题1： todo文本过长导致的样式问题
问题2：代码块全选剪切的问题
问题3：toolbar快速点击的问题
**注：所有问题都是在即时渲染模式下的，其他模式未测试**
> 即时渲染下的一些问题

- src/ts/upload/index.ts
> ✅ 修复201不算成功的问题

- src/ts/preview/index.ts
> fix: 预览模式下,工具栏不自动隐藏

- src/ts/hint/index.ts
- src/ts/wysiwyg/highlightToolbarWYSIWYG.ts
用鼠标选择编程语言后，输入焦点自动从语言输入框切换到代码输入框
> feat(wysiwys): 所见即所得模式下,鼠标选择编程语言后,自动聚焦到代码输入框

- src/assets/scss/_hint.scss
- src/assets/scss/_panel.scss
- src/assets/scss/_toolbar.scss
- src/ts/toolbar/setToolbar.ts
> fix :bug: : fix styles

- src/assets/scss/_hint.scss
- src/assets/scss/_panel.scss
- src/assets/scss/_toolbar.scss
- src/ts/toolbar/setToolbar.ts
Reverts Vanessa219/vditor#1199
> Revert "fix :bug: : fix styles"

- src/ts/util/fixBrowserBehavior.ts
> :bug: fix https://github.com/Vanessa219/vditor/issues/1289

- types/index.d.ts
> docs: 增加并更新 IOptions 的 JSDoc 内容

- CHANGELOG.md
- package.json
- src/ts/hint/index.ts
在form元素下的button按钮没有type属性，默认是submit属性，会导致点击提交表单
> 在form元素下的button按钮没有type属性

- src/ts/preview/index.ts
> Pref(优化)preview.actions为空不渲染

- src/ts/export/index.ts
> fix(export): 修复导出PDF时CDN配置不生效问题

- src/ts/markdown/plantumlRender.ts
#1452 plantuml支持超链接，使用object方式将svg内签到dom树中，可以让超链接生效
https://plantuml.com/zh/link
> #1452 使用object内嵌plantuml的svg元素，以支持plantuml的特殊语法

- src/ts/markdown/plantumlRender.ts
> fixbug https网站下请求http资源会被block

- src/ts/markdown/highlightRender.ts
- src/ts/ui/setCodeTheme.ts
> fix Vanessa219#1606

- src/ts/markdown/codeRender.ts
Fixes: https://github.com/Vanessa219/vditor/issues/1768
Behaviour after fix: https://github.com/user-attachments/assets/4936a606-7e5d-470f-873f-09d3b8453192
> Fixing: Clicking copy button in code block unintentionally expands it
