- src/assets/scss/_content.scss
> fix: menu misplaced when vditor is not first child

- src/assets/scss/_toolbar.scss
> 修复父元素自定义行高时工具栏垂直不居中

- src/ts/ui/initUI.ts
- types/index.d.ts
* PR 请提交到开发分支上
* 我们对编码风格有着较为严格的要求，请在阅读代码后模仿类似风格提交
在设置中添加 `minHeight` 属性，以允许在设置 `height` 为 `auto` 的情况下手动设置编辑区域的最小高度。
避免编辑区过于「扁」时影响视觉效果。
> 🎨 add minHeight

- src/ts/counter/index.ts
- src/ts/ir/process.ts
- src/ts/sv/inputEvent.ts
- src/ts/wysiwyg/afterRenderEvent.ts
- types/index.d.ts
9bdc88f：改进字数统计，去除末尾换行符（解决空内容长度显示为 1 的问题）。
API 变动：`counter.render` 的首个参数从接收长度改为直接接收字符串。
----
3356608：添加 label，使字数统计意义更明确，不易引起混淆；同时为添加其他意义（例如纯字符、HTML）的长度统计打基础。
API 变动：`counter.render` 可选的第三个参数接收 `counter` 的 label，默认值为 `"Markdown"`。
> 🎨 改进 Counter

- README.md
- src/index.ts
- src/ts/counter/index.ts
- src/ts/ir/process.ts
- src/ts/sv/inputEvent.ts
- src/ts/ui/initUI.ts
- src/ts/util/Options.ts
- src/ts/wysiwyg/afterRenderEvent.ts
- types/index.d.ts
允许通过设置 `options.counter: true` 来启用字数统计。
为 `Counter.render` 添加了第三个参数，以支持对于字数统计功能的后续改进，例如 #297 。对现有 API 无影响。
P.S. 建议使用 `Markdown: 12/100` 风格的字符统计标签，更为正式的同时也符合其他主流本地编辑器的做法。本 PR 不包括这一改动。
其他变化：其他组件应该使用 `vditor.options.counter != false` 而非 `vditor.options.counter > 0` 来判断字数统计的开启情况。
----
- 补充了 README 内容
- 统一了 README 风格
> ✨ 允许开启 counter 而不设置限值 & README 优化

- demo/extmdfile.html
- demo/mdtext/demo1.md
- demo/mdtext/demo2.md
- demo/mdtext/ko_KR.md
- demo/mdtext/zh_CN.md
Reading external markdown text.
> Demo for reading external markdown text

- src/ts/preview/index.ts
- src/ts/util/Options.ts
- types/index.d.ts
例如：
```ts
actions: [
"table",
"mobile",
{
text: "自定义",
click: () => {
console.log('custom');
}
}
]
```
- close https://github.com/Vanessa219/vditor/issues/569
* PR 请提交到开发分支上
* 我们对编码风格有着较为严格的要求，请在阅读代码后模仿类似风格提交
> feat: 增加预览工具条可配置且可自定义

- src/assets/scss/_toolbar.scss
- src/assets/scss/index.scss
light:
dark:
当 `--toolbar-divider-margin-top: 0px` 时会变成：
* PR 请提交到开发分支上
* 我们对编码风格有着较为严格的要求，请在阅读代码后模仿类似风格提交
> style: 优化分隔符样式

- src/ts/ir/process.ts
> fix: safari下选中文字添加标题文字会消失

- README.md
- README_en_US.md
- 提供Svelte demo代码
- 更新README支持Svelte框架
> docs :pencil: : Support Svelte

- src/ts/hint/index.ts
在firefox中使用所见即所得模式,编辑```插入代码,选择语言回车无效
控制台报错`i.startContainer.firstElementChild is null`
原因是range.startContainer在firefox和chrome表现不一致
在chrome中startContrainer是input的父元素,在firefox中是input本身
> fix: 修复所见即所得模式下,代码语言选择在firefox不工作

- src/ts/util/editorCommonEvent.ts
> fix: 在焦点更改后，代码选择列表不自动隐藏

- package-lock.json
- src/ts/toolbar/Emoji.ts
优化 Emoji.ts 中绑定事件方式为事件代理,在表情选项多的情况下,可以优化一定程度的性能
> 优化 Emoji.ts 中绑定事件方式为事件代理

- README.md
- src/ts/ir/index.ts
- src/ts/preview/index.ts
- src/ts/util/editorCommonEvent.ts
- types/index.d.ts
- #1220 改善图片预览问题，增加options->preview->showImage: boolean控制是否双击预览
- 增加options->previewImage函数获取触发的图片节点，参数img: HTMLImageElement
链接相关
- 增加options-> link属性，options->link->open: boolean控制点击打开链接，options->link->intercept函数控制点击的链接，参数 url: string
> feat: 图片相关&链接open

- src/ts/preview/index.ts
现在默认copy行为的提示是不正确, 因为只是复制到剪切板, 没有微信平台这些内容.
> fix: 修复preview.actions里面默认复制行为的错误提示

- src/ts/outline/index.ts
- src/ts/preview/index.ts
- types/index.d.ts
当前设置了 `options.preview.actions` 的预览页面的 `preview.element.lastElementChild` 指向了 `vditor-preview__action` 元素导致无法正常渲染, 现更改为使用 `preview.previeElement` 访问渲染内容容器
> Fix the issue of confusing preview element and actions element

- src/ts/markdown/codeRender.ts
在预览内容很多且包含很多代码片段的文档时，加载速度非常慢，有时会让整个页面卡死。
浏览器的性能分析报告如下：
布局耗时 36 秒，布局排班中的色块是分成很多段的，这说明触发了很多次布局。
点击跳转源码界面，e.innerText 这一行代码耗时最高：
由此可看出每次 `e.before(divElement)` 后获取元素的 innerText 都会重新布局一次。
解决方法是改成先批量获取 innerText，然后再批量插入新元素。优化后的效果如下，耗时大幅减少。
> perf: 优化代码块的渲染性能

- src/ts/sv/inputEvent.ts
- src/ts/sv/process.ts
尝试修复了下#1518，这个问题应该是在修复`1270`和`1269`时产生的，个人认为脚注自动复制全文对用户使用的影响更大，因此修复了下这个问题。
同样有关联的问题:https://github.com/Vanessa219/vditor/issues/1269#issuecomment-1208331988
> 修复SV模式下脚注下方输入文本出现渲染错误

- src/ts/sv/inputEvent.ts
- src/ts/sv/process.ts
- src/ts/toolbar/EditMode.ts
- src/ts/util/combineFootnote.ts
- 修复了 #1518 中所提到的脚注代码块会被文档提前的问题
- 修复 #1269 提到的 <```> 补全问题
- 修复了与 1518 类似的链接定义问题
**1518**
通过在处理脚注脚注添加到末尾前对所属同一脚注的部分进行合并
**1269**
交由lute进行渲染前，将所有脚注提到待处理文本最上方，避免lute解析```时错误的将脚注作为主体内容解析
**链接定义问题**
同1518处理方式
> 修复了一些关于脚注的问题

- src/ts/util/editorCommonEvent.ts
借用options.select自定义拓展选中浮窗，没有对应的钩子来隐藏浮窗，所以新增unSelect事件来进行隐藏。
> feat: 新增unSelect事件回调
